<?php
/**
 * Title: Portfolio: Contact
 * Slug: portfolio/contact
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","text_align_lg":"text-lg-center","mb_lg":"","pr":"3","pl":"3","pt_lg":"4","pr_lg":"5","pb_lg":"5","pl_lg":"6","rounded":"rounded","flex_align_items_lg":"align-items-lg-center","anchor":"contact"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='3'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg='5'  pb_lg='5'  pl_lg='6'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor='contact'  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pe-3 ps-3 pt-4 pe-lg-5 pb-5 ps-lg-6 text-center container-fluid rounded align-items-center" id="contact"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","mb_lg":"","display_lg":"d-lg-flex","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-1 row-cols-md-2 d-flex row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","bg_color":"#f7f7f7","text_align_lg":"text-lg-start","mb_lg":"","rounded":"rounded"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#f7f7f7'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined text-start col rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Got a porject ? Let's talk","html_tag":"h2","text_color":"primary","font_size":"0","font_weight":"font-weight-bold","mb_lg":"5"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-5 text-primary font-weight-bold 0">Got a porject ? Let's talk</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:contact-form-7/contact-form-selector {"id":1970,"title":"Contact form 1"} -->
<div class="wp-block-contact-form-7-contact-form-selector">[contact-form-7 id="1970" title="Contact form 1"]</div>
<!-- /wp:contact-form-7/contact-form-selector --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-center","mb_lg":"","rounded":"rounded"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined text-center col rounded"><!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-location-dot","title":"3131 Rockwell Lane, NC 27834","title_tag":"div","type":"none","iconbox_size":"medium","icon_color":"primary","icon_text_align_lg":"","title_size":"h5","title_color":"white","title_text_align_lg":"","desc_size":"h6","desc_font_weight":"font-weight-light","desc_text_align_lg":"","pt_lg":"4","pb_lg":"4","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 pt-4 pb-4 \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon text-primary text-center h3  \u0022  \u003e\u003ci class=\u0022fa-solid fa-location-dot   \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003cdiv class=\u0022blockstrap-iconbox-title text-white text-center h5   mb-0\u0022  \u003e3131 Rockwell Lane, NC 27834\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-location-dot'  title='3131 Rockwell Lane, NC 27834'  title_tag='div'  description=''  type='none'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type=''  iconbox_size='medium'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg=''  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color='white'  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg=''  title_pb=''  desc_size='h6'  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight='font-weight-light'  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg=''  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg=''  pb_lg='4'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-phone","title":"252-547-3532","title_tag":"div","type":"none","iconbox_size":"medium","icon_color":"primary","icon_text_align_lg":"","title_size":"h5","title_color":"white","title_text_align_lg":"","desc_size":"h6","desc_font_weight":"font-weight-light","desc_text_align_lg":"","pb_lg":"4","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 pb-4 \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon text-primary text-center h3  \u0022  \u003e\u003ci class=\u0022fa-solid fa-phone   \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003cdiv class=\u0022blockstrap-iconbox-title text-white text-center h5   mb-0\u0022  \u003e252-547-3532\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-phone'  title='252-547-3532'  title_tag='div'  description=''  type='none'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type=''  iconbox_size='medium'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg=''  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color='white'  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg=''  title_pb=''  desc_size='h6'  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight='font-weight-light'  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg=''  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='4'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-envelope","title":" youremail@example.com","title_tag":"div","type":"none","iconbox_size":"medium","icon_color":"primary","icon_text_align_lg":"","title_size":"h5","title_color":"white","title_text_align_lg":"","desc_size":"h6","desc_font_weight":"font-weight-light","desc_text_align_lg":"","mb_lg":"5","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 mb-5 \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon text-primary text-center h3  \u0022  \u003e\u003ci class=\u0022fa-solid fa-envelope   \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003cdiv class=\u0022blockstrap-iconbox-title text-white text-center h5   mb-0\u0022  \u003e youremail@example.com\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-envelope'  title=' youremail@example.com'  title_tag='div'  description=''  type='none'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type=''  iconbox_size='medium'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg=''  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color='white'  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg=''  title_pb=''  desc_size='h6'  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight='font-weight-light'  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg=''  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='5'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->