<?php
/**
 * Title: Portfolio - Default Header
 * Slug: portfolio/header-default
 * Categories: blockstrap-site-header
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","mb_lg":"","border":"0","border_type":"border-end"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type='border-end'  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined border-0 container-fluid border-end"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"","css_class":"fixed-header-start"} -->
[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='fixed-header-start' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row fixed-header-start"><!-- wp:blockstrap/blockstrap-widget-skip-links {"content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e"} -->
[bs_skip_links text1='Skip to main content'  hash1='main'  text2=''  hash2=''  text3=''  hash3=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-skip-links -->

<!-- wp:blockstrap/blockstrap-widget-navbar {"bg":"dark","bg_color":"#000000","cscos":true,"container":"navbar-dark","inner_container":"container","mb_lg":"","pr":"0","pl":"0","pr_lg":"2","pl_lg":"2"} -->
[bs_navbar bg='dark'  bg_color='#000000'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bgtus='false'  cscos='true'  container='navbar-dark'  inner_container='container'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='2'  pb_lg=''  pl_lg='2'  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom='' ]<nav class="navbar navbar-expand-lg pe-0 ps-0 pe-lg-2 ps-lg-2 bg-dark navbar-dark"><div class="wp-block-blockstrap-blockstrap-widget-navbar container"><!-- wp:blockstrap/blockstrap-widget-navbar-brand {"text":"","icon_image":"<?php echo esc_url( get_theme_file_uri( 'assets/images/logo-white.png' ) ); ?>","img_max_width":70,"custom_url":"/","brand_font_size":"0","bg_gradient":"linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)","bg_on_text":true,"mb":"0","mb_lg":"4","pl":"0","pl_lg":"3","rounded_size":"lg"} -->
[bs_navbar_brand text=''  icon_image='<?php echo esc_url( get_theme_file_uri( 'assets/images/logo-white.png' ) ); ?>'  img_max_width='70'  type='home'  custom_url='/'  text_color=''  brand_font_size='0'  brand_font_weight=''  brand_font_italic=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)'  bg_on_text='true'  mt=''  mr=''  mb='0'  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='4'  ml_lg=''  pt=''  pr=''  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='3'  border=''  rounded=''  rounded_size='lg'  shadow=''  css_class='' ]<a class="navbar-brand d-flex align-items-center mb-0 mb-lg-4 ps-0 ps-lg-3 rounded-lg" href="http://blockstrap.local"><img class="" alt="Site logo" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/logo-white.png' ) ); ?>" style="max-width:60px" width="70" height="50"/><span class="mb-0 0  "></span></a>[/bs_navbar_brand]
<!-- /wp:blockstrap/blockstrap-widget-navbar-brand -->

<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"1","flex_direction":"flex-column","font_size":"0","mr":"","ml":"","mr_lg":"","ml_lg":"","rounded_size":"lg"} -->
[bs_nav inside_navbar='1'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='0'  font_size_custom=''  bg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  width=''  css_class='' ]<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav_1" aria-label="Open menu"><span class="navbar-toggler-icon"></span></button><div class="wp-block-blockstrap-blockstrap-widget-nav collapse navbar-collapse" id="navbarNav_1"><ul class="wp-block-blockstrap-blockstrap-widget-nav navbar-nav rounded-lg flex-column 0"><!-- wp:blockstrap/blockstrap-widget-nav-item {"page_id":"70","custom_url":"#about","text":"Home","icon_class":"fa-solid fa-house","text_color":"white","ml":"0","content":"\u003ca href=\u0022#http://blockstrap.local\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fa-solid fa-house me-2\u0022\u003e\u003c/i\u003eHome\u003c/a\u003e"} -->
[bs_nav_item type='home'  page_id='70'  post_id=''  custom_url='#about'  text='Home'  icon_class='fa-solid fa-house'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","page_id":"1963","custom_url":"#about","text":"About","icon_class":"fa-solid fa-user","text_color":"white","content":"\u003ca href=\u0022##about\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fa-solid fa-user me-2\u0022\u003e\u003c/i\u003eAbout\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id='1963'  post_id=''  custom_url='#about'  text='About'  icon_class='fa-solid fa-user'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#services","text":"Services","icon_class":"fa-solid fa-laptop","text_color":"white","content":"\u003ca href=\u0022##services\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fa-solid fa-laptop me-2\u0022\u003e\u003c/i\u003eServices\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#services'  text='Services'  icon_class='fa-solid fa-laptop'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#portfolio","text":"Portfolio","icon_class":"fa-solid fa-images","text_color":"white","content":"\u003ca href=\u0022##portfolio\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fa-solid fa-images me-2\u0022\u003e\u003c/i\u003ePortfolio\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#portfolio'  text='Portfolio'  icon_class='fa-solid fa-images'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#blog","text":"Blog","icon_class":"fa-solid fa-table-columns","text_color":"white","content":"\u003ca href=\u0022##blog\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fa-solid fa-table-columns me-2\u0022\u003e\u003c/i\u003eBlog\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#blog'  text='Blog'  icon_class='fa-solid fa-table-columns'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","page_id":"1858","custom_url":"#contact","text":"Contact","icon_class":"fa-regular fa-envelope","text_color":"white","content":"\u003ca href=\u0022##contact\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fa-regular fa-envelope me-2\u0022\u003e\u003c/i\u003eContact\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id='1858'  post_id=''  custom_url='#contact'  text='Contact'  icon_class='fa-regular fa-envelope'  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div><script>jQuery("#navbarNav_1").on("show.bs.collapse", function () {jQuery("#navbarNav_1").closest(".bg-transparent-until-scroll,.bg-transparent").addClass("nav-menu-open");});jQuery("#navbarNav_1").on("hidden.bs.collapse", function () {jQuery("#navbarNav_1").closest(".bg-transparent-until-scroll,.bg-transparent").removeClass("nav-menu-open");});</script>[/bs_nav]
<!-- /wp:blockstrap/blockstrap-widget-nav --></div></nav>[/bs_navbar]
<!-- /wp:blockstrap/blockstrap-widget-navbar --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->